<?php
Yii::setAlias('@common', dirname(__DIR__));
Yii::setAlias('@frontend', dirname(dirname(__DIR__)) . '/frontend');
Yii::setAlias('@ca', dirname(dirname(__DIR__)) . '/ca');
Yii::setAlias('@govrel', dirname(dirname(__DIR__)) . '/govrel');
Yii::setAlias('@iko', dirname(dirname(__DIR__)) . '/iko');
Yii::setAlias('@osp', dirname(dirname(__DIR__)) . '/osp');
Yii::setAlias('@planning', dirname(dirname(__DIR__)) . '/planning');
Yii::setAlias('@ppl', dirname(dirname(__DIR__)) . '/ppl');
Yii::setAlias('@ospm', dirname(dirname(__DIR__)) . '/ospm');
Yii::setAlias('@netpro', dirname(dirname(__DIR__)) . '/netpro');
Yii::setAlias('@sc', dirname(dirname(__DIR__)) . '/sc');
Yii::setAlias('@am', dirname(dirname(__DIR__)) . '/am');
Yii::setAlias('@os', dirname(dirname(__DIR__)) . '/os');
Yii::setAlias('@ap', dirname(dirname(__DIR__)) . '/ap');
Yii::setAlias('@usermanagement', dirname(dirname(__DIR__)) . '/usermanagement');
Yii::setAlias('@console', dirname(dirname(__DIR__)) . '/console');
Yii::setAlias('@commonpath', '/im/common');
Yii::setAlias('@corporate', dirname(dirname(__DIR__)) . '/corporate');
Yii::setAlias('@oci', dirname(dirname(__DIR__)) . '/oci');
Yii::setAlias('@inbound', dirname(dirname(__DIR__)) . '/inbound');
Yii::setAlias('@outbound', dirname(dirname(__DIR__)) . '/outbound');
Yii::setAlias('@instruction', dirname(dirname(__DIR__)) . '/instruction');
Yii::setAlias('@divisisatu', dirname(dirname(__DIR__)) . '/divisisatu');
Yii::setAlias('@divisidua', dirname(dirname(__DIR__)) . '/divisidua');
Yii::setAlias('@divisitiga', dirname(dirname(__DIR__)) . '/divisitiga');
Yii::setAlias('@setting', dirname(dirname(__DIR__)) . '/setting');
Yii::setAlias('@grflost', dirname(dirname(__DIR__)) . '/grflost');
Yii::setAlias('@api', dirname(dirname(__DIR__)) . '/api');
